import React, { useEffect, useState } from 'react';
import { AlertTriangle, Filter, RefreshCw, Search, ShieldAlert } from 'lucide-react';
import { apiRequest } from '../services/api';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { RiskBadge } from '../components/ui/RiskBadge';
import type { Alert, AlertStatus, RiskLevel } from '../types';

const statusOptions: Array<AlertStatus | 'ALL'> = [
  'ALL',
  'NEW',
  'ACKNOWLEDGED',
  'INVESTIGATING',
  'RESOLVED',
  'DISMISSED',
];

const severityOptions: Array<RiskLevel | 'ALL'> = ['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [statusFilter, setStatusFilter] = useState<AlertStatus | 'ALL'>('ALL');
  const [severityFilter, setSeverityFilter] = useState<RiskLevel | 'ALL'>('ALL');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchAlerts = async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({ limit: '100' });
      if (statusFilter !== 'ALL') params.set('status', statusFilter);
      if (severityFilter !== 'ALL') params.set('severity', severityFilter);
      setAlerts(await apiRequest<Alert[]>(`/alerts?${params.toString()}`));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load alerts.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [statusFilter, severityFilter]);

  const visibleAlerts = alerts.filter((alert) => {
    const term = search.trim().toLowerCase();
    return !term || [alert.title, alert.transaction_id, alert.customer_id, alert.description]
      .some((value) => value.toLowerCase().includes(term));
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-rose-600" />
            Fraud Alerts
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">Alerts generated by the risk-scoring pipeline for your organization.</p>
        </div>
        <Button variant="outline" size="sm" onClick={fetchAlerts} isLoading={loading}>
          <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
          Refresh
        </Button>
      </div>

      <Card className="!p-4">
        <div className="flex flex-col lg:flex-row gap-3 lg:items-center lg:justify-between">
          <div className="relative w-full lg:w-80">
            <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400" />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search title, transaction, customer..."
              className="w-full pl-9 pr-4 py-1.5 text-xs border border-slate-300 rounded-btn focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <Filter className="w-4 h-4 text-slate-400" />
            <select
              aria-label="Filter alerts by status"
              value={statusFilter}
              onChange={(event) => setStatusFilter(event.target.value as AlertStatus | 'ALL')}
              className="text-xs border border-slate-300 rounded-btn px-2.5 py-1.5 bg-white"
            >
              {statusOptions.map((status) => <option key={status} value={status}>{status === 'ALL' ? 'All statuses' : status}</option>)}
            </select>
            <select
              aria-label="Filter alerts by severity"
              value={severityFilter}
              onChange={(event) => setSeverityFilter(event.target.value as RiskLevel | 'ALL')}
              className="text-xs border border-slate-300 rounded-btn px-2.5 py-1.5 bg-white"
            >
              {severityOptions.map((severity) => <option key={severity} value={severity}>{severity === 'ALL' ? 'All severities' : severity}</option>)}
            </select>
          </div>
        </div>
      </Card>

      <Card className="!p-0 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-slate-500 font-semibold uppercase tracking-wider">
                <th className="py-3 px-4">Alert</th>
                <th className="py-3 px-4">Transaction</th>
                <th className="py-3 px-4">Severity</th>
                <th className="py-3 px-4">Risk score</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4">Created</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr><td colSpan={6} className="text-center py-10 text-slate-500">Loading alerts...</td></tr>
              ) : error ? (
                <tr>
                  <td colSpan={6} className="text-center py-10 text-red-600">
                    <p>{error}</p>
                    <Button variant="outline" size="sm" className="mt-3" onClick={fetchAlerts}>Retry</Button>
                  </td>
                </tr>
              ) : visibleAlerts.length === 0 ? (
                <tr>
                  <td colSpan={6} className="text-center py-10 text-slate-500">
                    <AlertTriangle className="w-7 h-7 mx-auto mb-2 text-slate-300" />
                    No alerts match the current filters.
                  </td>
                </tr>
              ) : visibleAlerts.map((alert) => (
                <tr key={alert.id} className="hover:bg-slate-50/80">
                  <td className="py-3 px-4 max-w-sm">
                    <p className="font-semibold text-slate-900">{alert.title}</p>
                    <p className="text-slate-500 mt-0.5 truncate">{alert.description}</p>
                  </td>
                  <td className="py-3 px-4">
                    <p className="font-mono text-slate-800">{alert.transaction_id}</p>
                    <p className="text-slate-500 mt-0.5">{alert.customer_id}</p>
                  </td>
                  <td className="py-3 px-4"><RiskBadge level={alert.severity} /></td>
                  <td className="py-3 px-4 font-semibold text-slate-900">{Math.round(alert.risk_score)} / 100</td>
                  <td className="py-3 px-4 text-slate-700">{alert.status}</td>
                  <td className="py-3 px-4 text-slate-500 whitespace-nowrap">{new Date(alert.created_at).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};

export default AlertsPage;
